version: '3.8'
networks: # to create a custom bridge
    ashubr111:
services:ashuapp007:
    image: ashuciapp:v1
    build: .
    container_name: ashucic1
    ports:
        - "1111:80"
    restart: always
    networks: # use bridge created above- ashubr111
        - ashubr111
